---
- name: zabbix
  box: trombik/ansible-ubuntu-18.04-amd64
  hostname: zabbix.dnd.com.br
  ipaddress: 192.168.1.20
  memory: 1024
  cpus: 1
  provision: provision/ansible/zabbix.yaml

- name: prometheus
  box: trombik/ansible-centos-7.3-x86_64
  hostname: prometheus.dnd.com.br
  ipaddress: 192.168.1.21
  memory: 1024
  cpus: 1
  provision: provision/ansible/prometheus.yaml
