Vagrant.configure("2") do |config|
   config.vm.box = "generic/ubuntu2010"
   config.vm.provider "virtualbox" do |vb|
       vb.memory = 2048
       vb.cpus = 1
    end

config.vm.define "zabbix-server" do |zabbix|
    zabbix.vm.network "public_network", ip: "192.168.1.86",  bridge: "wlp6s0"
    zabbix.vm.network "forwarded_port", guest:6666, host: 6666
#    zabbix.vm.synced_folder ".configs", "/home/vagrant/zabbix-stuff"

#    zabbix.vm.provision "shell",
#    inline: $zabbix_script

#    zabbix.vm.provision "shell",
#    inline: $mysql_script
    end
end
